**NUMPY**

In [2]:
import numpy as np

In [ ]:
a=np.array([12,34,56])
b=np.array([3,4,5])


In [ ]:
a*b

array([ 36, 136, 280])

In [ ]:
#numpy arrayleri verileri aynı tipte olmaya zorlar
x=np.array([3,4,5,6.8])
x

array([3. , 4. , 5. , 6.8])

In [ ]:
np.zeros(8)#sıfırlardan oluşan bir array

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(5,dtype=int)#birlerden oluşan bir array

array([1, 1, 1, 1, 1])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [ ]:
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

In [ ]:
np.linspace(0,1,40)

array([0.        , 0.02564103, 0.05128205, 0.07692308, 0.1025641 ,
       0.12820513, 0.15384615, 0.17948718, 0.20512821, 0.23076923,
       0.25641026, 0.28205128, 0.30769231, 0.33333333, 0.35897436,
       0.38461538, 0.41025641, 0.43589744, 0.46153846, 0.48717949,
       0.51282051, 0.53846154, 0.56410256, 0.58974359, 0.61538462,
       0.64102564, 0.66666667, 0.69230769, 0.71794872, 0.74358974,
       0.76923077, 0.79487179, 0.82051282, 0.84615385, 0.87179487,
       0.8974359 , 0.92307692, 0.94871795, 0.97435897, 1.        ])

In [ ]:
np.random.randint(3,20,(4,4))

array([[17,  3,  4, 16],
       [17, 11,  8, 18],
       [10, 19, 19,  3],
       [ 7,  8, 17,  6]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**NUMPY BİÇİMLENDİRME**

In [ ]:
np.random.randint(3,20,(5,5))

array([[13,  3,  6,  6, 16],
       [11, 10, 15,  3,  8],
       [ 7, 14, 13, 18, 16],
       [ 3, 11, 10, 16,  8],
       [13, 18, 11, 19,  9]])

In [ ]:
a=np.random.randint(9,size=10)

In [ ]:
a

array([4, 7, 3, 8, 3, 0, 5, 7, 8, 5])

In [ ]:
a.ndim #ka. tane köşeli parantez var

1

In [ ]:
a.shape #boyutlarını öğrenmemiz için kullanılır

(10,)

In [ ]:
a.size

10

In [ ]:
d=np.random.randint(8,size=(7,5))

In [ ]:
d

array([[7, 1, 5, 1, 3],
       [1, 6, 3, 5, 0],
       [5, 6, 2, 1, 0],
       [7, 1, 2, 4, 6],
       [2, 4, 5, 6, 3],
       [0, 4, 1, 1, 2],
       [4, 0, 5, 0, 6]])

In [ ]:
d.ndim

2

In [ ]:
a=np.array([2,3,4,5])
b=np.array([5,6,7,8])

In [ ]:
a

array([2, 3, 4, 5])

In [ ]:
b

array([5, 6, 7, 8])

In [ ]:
np.concatenate([a,b])#iki numpy arrayını birleştirir.

array([2, 3, 4, 5, 5, 6, 7, 8])

In [3]:
a=np.random.randint(8,size=(3,5,2))

In [4]:
a

array([[[1, 6],
        [3, 0],
        [1, 6],
        [4, 4],
        [0, 6]],

       [[3, 4],
        [6, 6],
        [1, 4],
        [2, 0],
        [3, 0]],

       [[1, 7],
        [5, 5],
        [4, 3],
        [0, 3],
        [5, 3]]])

In [5]:
a.ndim

3

In [6]:
a.shape

(3, 5, 2)

In [7]:
a.size

30

In [8]:
a.dtype

dtype('int64')

In [9]:
d=np.array([[1,2,3],[4,5,6]])
e=np.array([[7,8,9],[10,11,12]])


In [10]:
d.ndim

2

In [11]:
e.ndim

2

In [12]:
np.concatenate([d,e])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.concatenate([d,e],axis=1)#iki arrayı yanyana birleştirdi.

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [15]:
x=np.array([1,2,3])
y=np.array([[7,8,9],[12,13,14]])

In [17]:
np.vstack([x,y])#(eşit sütun sayısına sahip olanları birleştirir.)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [12, 13, 14]])

In [18]:
a=np.array([[12],[13]])
b=np.array([[1,2,3],[4,5,6]])


In [19]:
np.hstack([a,b])#satır sayısı aynı olduğunda uygulanır.

array([[12,  1,  2,  3],
       [13,  4,  5,  6]])

In [21]:
x=np.random.randint(9,size=12)

In [22]:
x

array([5, 1, 0, 0, 5, 2, 3, 3, 5, 2, 2, 5])

In [24]:
y=np.random.randint(9,size=(3,4))

In [25]:
y

array([[6, 2, 6, 2],
       [6, 0, 0, 1],
       [1, 2, 2, 3]])

In [29]:
y[2,3]

np.int64(3)

In [30]:
y[2,1]=13

In [31]:
y

array([[ 6,  2,  6,  2],
       [ 6,  0,  0,  1],
       [ 1, 13,  2,  3]])

In [32]:
z=np.arange(5,20)

In [33]:
z

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
z[3:7]

array([ 8,  9, 10, 11])

In [36]:
z[::2]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [37]:
z[::]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
z[1::2]

array([ 6,  8, 10, 12, 14, 16, 18])

In [39]:
u=np.random.randint(5,20,size=(3,5))

In [40]:
u

array([[14, 12,  5,  5, 19],
       [10, 19, 15,  6,  8],
       [14,  9, 12, 16, 11]])

In [41]:
u[:,0] #u[satır,sütun]

array([14, 10, 14])

In [42]:
u[0,:]

array([14, 12,  5,  5, 19])

In [43]:
u[:2,:3]

array([[14, 12,  5],
       [10, 19, 15]])

In [44]:
u[:2,::]

array([[14, 12,  5,  5, 19],
       [10, 19, 15,  6,  8]])