**NUMPY ARRAY'İ OLUŞTURMAK**

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])

In [2]:
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
a=np.array([1,2,3,4,5],dtype="float32")#hepsini tek tip yapar yerden tasarruf etmek için

In [5]:
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5),dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [9]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.normal(10,4,(3,4))#standart sapması 10,ortalaması 4 3'e dörtlük matris

array([[10.43144295,  8.28992101, 10.30225146,  7.78573338],
       [ 8.08090142,  2.47350218,  4.34183821,  5.20965094],
       [15.02867364,  9.14241543, 11.84940235,  3.52956762]])

In [12]:
np.random.randint(0,10,(3,3))

array([[0, 0, 2],
       [7, 2, 8],
       [9, 0, 4]])

In [13]:
a=np.random.randint(10,size=10)

In [14]:
a.ndim #boyutunu ayarlamak için

1

In [15]:
a.shape

(10,)

In [16]:
b=np.random.randint(10,size=(3,5))

In [17]:
b

array([[6, 5, 0, 7, 2],
       [8, 9, 1, 1, 6],
       [6, 7, 3, 1, 0]])

In [18]:
b.ndim

2

In [19]:
b.shape

(3, 5)

In [20]:
b.size

15

In [21]:
b.dtype

dtype('int64')

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,10).reshape((3,3))#tek boyutluyu istediğim boyuta getirmek için re shape kullanılır.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
c=np.arange(1,10)

In [25]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
c=c.reshape((1,9))

In [27]:
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [28]:
c.ndim

2

In [29]:
x=np.array([1,2,3])
y=np.array([4,5,6])


In [30]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [31]:
z=np.array([7,8,9])


In [32]:
np.concatenate([x,y,z]) #birleştirmek için concatenate kullanırız

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a=np.random.randint(3,size=(3,3))

In [34]:
np.concatenate([a,a])

array([[1, 1, 0],
       [2, 0, 0],
       [1, 1, 2],
       [1, 1, 0],
       [2, 0, 0],
       [1, 1, 2]])

In [35]:
np.concatenate([a,a],axis=0)#ssatır bazında birleştirme yapar

array([[1, 1, 0],
       [2, 0, 0],
       [1, 1, 2],
       [1, 1, 0],
       [2, 0, 0],
       [1, 1, 2]])

In [36]:
np.concatenate([a,a],axis=1)

array([[1, 1, 0, 1, 1, 0],
       [2, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 2]])

In [37]:
a=np.array([1,2,3,4,5,6,7,99,99])

In [38]:
np.split(a,[3,5])#numpy arrayini bölmek istersem kullanılır.

[array([1, 2, 3]), array([4, 5]), array([ 6,  7, 99, 99])]

In [39]:
a,b,c=np.split(a,[3,5])

In [40]:
print(a)
print(b)
print(c)

[1 2 3]
[4 5]
[ 6  7 99 99]


In [41]:
z=np.arange(16).reshape(4,4)

In [42]:
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
np.vsplit(z,[2])#vsplit:satırı ortadan ikiye böler

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [44]:
a,b=np.vsplit(z,[2])
print(a)
print(b)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [45]:
a,b=np.hsplit(z,[2]) #hsplit:sütun bazında bölme yapar

In [46]:
print(a)
print(b)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [47]:
n=np.array([2,6,8,1,4])


In [48]:
np.sort(n)#arrayi sıralamak için


array([1, 2, 4, 6, 8])

In [49]:
x=n.sort() #numpy içinde çağırmadığı zaman tipini değiştirmiş oluyor.
x
type(x)

NoneType

In [50]:
m=np.random.normal(20,5,(3,3))

In [51]:
m

array([[21.42425026, 14.55682269, 23.35791182],
       [13.00867979, 18.94438048, 15.68466775],
       [19.12371474, 21.44749727, 16.99002141]])

In [52]:
np.sort(m,axis=1)

array([[14.55682269, 21.42425026, 23.35791182],
       [13.00867979, 15.68466775, 18.94438048],
       [16.99002141, 19.12371474, 21.44749727]])

In [53]:
np.sort(m,axis=0)

array([[13.00867979, 14.55682269, 15.68466775],
       [19.12371474, 18.94438048, 16.99002141],
       [21.42425026, 21.44749727, 23.35791182]])

In [54]:
y=np.random.randint(10,size=5)

In [55]:
y

array([0, 3, 8, 9, 5])

In [56]:
y[0]

np.int64(0)

In [57]:
x=np.random.randint(10,size=(5,5))



In [58]:
x

array([[2, 3, 5, 3, 6],
       [3, 2, 8, 7, 8],
       [9, 6, 4, 9, 1],
       [2, 5, 5, 8, 5],
       [8, 6, 3, 5, 5]])

In [59]:
x[0,1]

np.int64(3)

In [60]:
x[0,3]=23

In [61]:
x

array([[ 2,  3,  5, 23,  6],
       [ 3,  2,  8,  7,  8],
       [ 9,  6,  4,  9,  1],
       [ 2,  5,  5,  8,  5],
       [ 8,  6,  3,  5,  5]])

In [62]:
x[1,4]=2.2
#eğer bir arrayimin içinde bir tane bile farklı türden bir veri varsa bu farklı türden veriye göre bütün numpy arrayini düzenler
#ama eğer dışardan bir müdaheke yaparsam gelen farklı tipteki veriyi içerdeki verilere göre düzenler

In [63]:
x

array([[ 2,  3,  5, 23,  6],
       [ 3,  2,  8,  7,  2],
       [ 9,  6,  4,  9,  1],
       [ 2,  5,  5,  8,  5],
       [ 8,  6,  3,  5,  5]])

In [64]:
x[:,0]#bütün satırları seç bu satırlar arasından ilk sütünu getir

array([2, 3, 9, 2, 8])

In [65]:
x[0,:]#0'ncı satır ve tüm sütünlar

array([ 2,  3,  5, 23,  6])

In [66]:
x[1,:]

array([3, 2, 8, 7, 2])

In [67]:
x[0:2,0:3]

array([[2, 3, 5],
       [3, 2, 8]])

In [68]:
x[:,:2]

array([[2, 3],
       [3, 2],
       [9, 6],
       [2, 5],
       [8, 6]])

In [69]:
z=np.random.randint(10,size=(5,5))

In [70]:
z

array([[8, 6, 1, 5, 7],
       [4, 2, 0, 2, 2],
       [5, 9, 6, 5, 2],
       [8, 6, 0, 4, 0],
       [5, 6, 0, 2, 0]])

In [71]:
alt_a=z[0:3,0:2]

In [72]:
alt_a

array([[8, 6],
       [4, 2],
       [5, 9]])

In [73]:
alt_a[0,0]=123
alt_a[1,1]=200

In [74]:
alt_a

array([[123,   6],
       [  4, 200],
       [  5,   9]])

In [75]:
z #alt kümede yaptığım bir işlem orijinal arrayimi de değiştiriyor
#bunu engellemek için copy metodunu kullanıyoruz.

array([[123,   6,   1,   5,   7],
       [  4, 200,   0,   2,   2],
       [  5,   9,   6,   5,   2],
       [  8,   6,   0,   4,   0],
       [  5,   6,   0,   2,   0]])

In [76]:
r=np.random.randint(9,size=(3,3))


In [77]:
r

array([[1, 5, 0],
       [6, 0, 8],
       [6, 1, 2]])

In [78]:
alt_b=r[0:3,0:2].copy()

In [79]:
alt_b[0,0]=123

In [80]:
alt_b

array([[123,   5],
       [  6,   0],
       [  6,   1]])

In [81]:
r

array([[1, 5, 0],
       [6, 0, 8],
       [6, 1, 2]])

**FANCY INDEX İLE ELEMANLARA  ERİŞMEK**

In [ ]:
#tek boyutta fancy

In [82]:
v=np.arange(0,30,3)

In [83]:
[v[1],v[2],v[3]]

[np.int64(3), np.int64(6), np.int64(9)]

In [84]:
al_getir=[1,3,5]

In [85]:
v[al_getir]

array([ 3,  9, 15])

In [89]:
n=np.random.randint(9,size=(3,3))
print(n)
satir=np.array([0,1])
sutun=np.array([1,2])


[[3 1 7]
 [3 3 4]
 [0 5 1]]


array([1, 4])

In [90]:
n[satir,sutun]

array([1, 4])

In [91]:
n

array([[3, 1, 7],
       [3, 3, 4],
       [0, 5, 1]])

In [92]:
n[0:,sutun] # 0'ncı satırı alır.1 ve 2. sütünları seçer

array([[1, 7],
       [3, 4],
       [5, 1]])

In [93]:
n[0:,[1,2]]

array([[1, 7],
       [3, 4],
       [5, 1]])

**KOŞULLU ELEMAN İŞLEMLERİ**

In [94]:
x=np.arange(0,5,1)

In [95]:
x

array([0, 1, 2, 3, 4])

In [96]:
x<3

array([ True,  True,  True, False, False])

In [97]:
x[x<3]

array([0, 1, 2])

In [98]:
x*2

array([0, 2, 4, 6, 8])

In [99]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [ ]:
#ufunc numpy da array üzerinde yaptığım amtematiksel işlemleri tanımlamak için kullanılır.

In [100]:
np.subtract(x,1)

array([-1,  0,  1,  2,  3])

In [101]:
np.add(x,2)

array([2, 3, 4, 5, 6])

In [102]:
np.multiply(x,3)

array([ 0,  3,  6,  9, 12])

In [103]:
np.divide(x,2)

array([0. , 0.5, 1. , 1.5, 2. ])

In [104]:
np.power(x,3)

array([ 0,  1,  8, 27, 64])

In [105]:
np.mod(x,3)

array([0, 1, 2, 0, 1])

In [106]:
np.absolute(np.array([-4]))

array([4])

In [107]:
np.sin(360)

np.float64(0.9589157234143065)

In [108]:
np.log(v)

/tmp/ipython-input-957696640.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(v)


array([      -inf, 1.09861229, 1.79175947, 2.19722458, 2.48490665,
       2.7080502 , 2.89037176, 3.04452244, 3.17805383, 3.29583687])

In [109]:
np.log2(v)

/tmp/ipython-input-3375032256.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(v)


array([      -inf, 1.5849625 , 2.5849625 , 3.169925  , 3.5849625 ,
       3.9068906 , 4.169925  , 4.39231742, 4.5849625 , 4.7548875 ])

In [110]:
?np #numoy ın ana dökümantasyonuna erişmek için.

5*x0+x1=12
********
x0+3*x1=10


In [112]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [113]:
a

array([[5, 1],
       [1, 3]])

In [114]:
b

array([12, 10])

In [115]:
x=np.linalg.solve(a,b)

In [116]:
x

array([1.85714286, 2.71428571])